package com.selfwg.app.ui

import android.content.Context
import com.selfwg.app.data.Prefs

/** Alle sichtbaren Texte – zweisprachig (DE/EN). */
data class Strings(
    val settings: String,
    val done: String,
    val cancel: String,
    val save: String,
    val next: String,
    val delete: String,
    // Status
    val connected: String,
    val connecting: String,
    val disconnected: String,
    val tunnelLabel: String,
    val serverLabel: String,
    val tunnelActive: String,
    val tunnelOff: String,
    // Tunnel-Liste
    val tunnelsSection: String,
    val noTunnelHint: String,
    val addTunnel: String,
    // Import
    val addTunnelTitle: String,
    val scanQr: String,
    val scanQrSub: String,
    val chooseFile: String,
    val chooseFileSub: String,
    val pasteText: String,
    val pasteTextSub: String,
    val pasteTitle: String,
    val nameTitle: String,
    // Edit
    val editTitle: String,
    val fieldName: String,
    val deleteTitle: String,
    val deleteMsg: String,
    // Feld-Labels + Beschreibungen
    val lPrivateKey: String, val dPrivateKey: String,
    val lAddress: String, val dAddress: String,
    val lDns: String, val dDns: String,
    val lMtu: String, val dMtu: String,
    val lPublicKey: String, val dPublicKey: String,
    val lPresharedKey: String, val dPresharedKey: String,
    val lEndpoint: String, val dEndpoint: String,
    val lAllowedIps: String, val dAllowedIps: String,
    val lKeepalive: String, val dKeepalive: String,
    // Apps / Split-Tunnel
    val appsSection: String,
    val appsInfo: String,
    val appModeAll: String,
    val appModeInclude: String,
    val appModeExclude: String,
    val chooseApps: String,
    val appsSelected: String,
    val searchApps: String,
    // Einstellungen
    val biometricTitle: String,
    val biometricSub: String,
    val autoBootTitle: String,
    val autoBootSub: String,
    val watchdogInfo: String,
    val languageTitle: String,
    // Toasts
    val tConfigTooBig: String,
    val tInvalidConfig: String,
    val tFileTooBig: String,
    val tFileError: String,
    val tAdded: String,
    val tSaved: String,
    val tDeleted: String,
)

object I18n {
    fun get(ctx: Context): Strings = if (Prefs.language(ctx) == "en") EN else DE

    private val DE = Strings(
        settings = "Einstellungen", done = "Fertig", cancel = "Abbrechen", save = "Speichern",
        next = "Weiter", delete = "Loeschen",
        connected = "Verbunden", connecting = "Verbindet …", disconnected = "Getrennt",
        tunnelLabel = "Tunnel", serverLabel = "Server", tunnelActive = "Tunnel aktiv", tunnelOff = "Tunnel aus",
        tunnelsSection = "Tunnel",
        noTunnelHint = "Noch kein Tunnel. Importiere eine WireGuard-Config aus WG-Easy.",
        addTunnel = "Tunnel hinzufuegen",
        addTunnelTitle = "Tunnel hinzufuegen",
        scanQr = "QR-Code scannen", scanQrSub = "WG-Easy QR-Code abscannen",
        chooseFile = "Datei waehlen", chooseFileSub = "Eine .conf-Datei laden",
        pasteText = "Text einfuegen", pasteTextSub = "Config-Text manuell einfuegen",
        pasteTitle = "Config einfuegen", nameTitle = "Name fuer den Tunnel",
        editTitle = "Tunnel bearbeiten", fieldName = "Name",
        deleteTitle = "Tunnel loeschen?", deleteMsg = "wird entfernt.",
        lPrivateKey = "Privater Schluessel", dPrivateKey = "Dein geheimer Schluessel. Niemals weitergeben.",
        lAddress = "Adresse", dAddress = "Deine IP im Tunnel, z. B. 10.8.0.2/32.",
        lDns = "DNS", dDns = "Namensaufloeser im Tunnel, z. B. 1.1.1.1.",
        lMtu = "MTU", dMtu = "Paketgroesse. Leer lassen, wenn unsicher (Standard ~1420).",
        lPublicKey = "Oeffentlicher Schluessel (Server)", dPublicKey = "Identitaet des Servers.",
        lPresharedKey = "Vorab-Schluessel", dPresharedKey = "Optionaler Zusatzschluessel fuer mehr Sicherheit.",
        lEndpoint = "Endpunkt", dEndpoint = "Adresse des Servers, z. B. vpn.ss-its.de:51820.",
        lAllowedIps = "Erlaubte IPs", dAllowedIps = "Welcher Verkehr in den Tunnel geht. 0.0.0.0/0 = alles.",
        lKeepalive = "Keepalive", dKeepalive = "Haelt die Verbindung wach (Sekunden), z. B. 25.",
        appsSection = "Apps (Split-Tunnel)",
        appsInfo = "Lege fest, welche Apps den Tunnel nutzen.",
        appModeAll = "Alle Apps", appModeInclude = "Nur diese", appModeExclude = "Alle ausser diese",
        chooseApps = "Apps waehlen", appsSelected = "ausgewaehlt", searchApps = "Suchen",
        biometricTitle = "Mit Fingerabdruck schuetzen",
        biometricSub = "App-Start per Fingerabdruck/Geraetesperre sichern.",
        autoBootTitle = "Nach Neustart verbinden",
        autoBootSub = "Automatisch verbinden, wenn das Handy neu startet.",
        watchdogInfo = "Der Waechter prueft alle 60 Sek und zusaetzlich alle 15 Min, ob die Server-IP " +
            "gewechselt hat, und verbindet dann automatisch neu.",
        languageTitle = "Sprache",
        tConfigTooBig = "Config zu gross", tInvalidConfig = "Ungueltige Config – bitte pruefen.",
        tFileTooBig = "Datei zu gross", tFileError = "Datei konnte nicht gelesen werden.",
        tAdded = "Tunnel hinzugefuegt", tSaved = "Gespeichert", tDeleted = "Geloescht",
    )

    private val EN = Strings(
        settings = "Settings", done = "Done", cancel = "Cancel", save = "Save",
        next = "Next", delete = "Delete",
        connected = "Connected", connecting = "Connecting …", disconnected = "Disconnected",
        tunnelLabel = "Tunnel", serverLabel = "Server", tunnelActive = "Tunnel active", tunnelOff = "Tunnel off",
        tunnelsSection = "Tunnels",
        noTunnelHint = "No tunnel yet. Import a WireGuard config from WG-Easy.",
        addTunnel = "Add tunnel",
        addTunnelTitle = "Add tunnel",
        scanQr = "Scan QR code", scanQrSub = "Scan the WG-Easy QR code",
        chooseFile = "Choose file", chooseFileSub = "Load a .conf file",
        pasteText = "Paste text", pasteTextSub = "Paste config text manually",
        pasteTitle = "Paste config", nameTitle = "Name for the tunnel",
        editTitle = "Edit tunnel", fieldName = "Name",
        deleteTitle = "Delete tunnel?", deleteMsg = "will be removed.",
        lPrivateKey = "Private key", dPrivateKey = "Your secret key. Never share it.",
        lAddress = "Address", dAddress = "Your IP inside the tunnel, e.g. 10.8.0.2/32.",
        lDns = "DNS", dDns = "Name resolver inside the tunnel, e.g. 1.1.1.1.",
        lMtu = "MTU", dMtu = "Packet size. Leave empty if unsure (default ~1420).",
        lPublicKey = "Public key (server)", dPublicKey = "Identity of the server.",
        lPresharedKey = "Preshared key", dPresharedKey = "Optional extra key for more security.",
        lEndpoint = "Endpoint", dEndpoint = "Address of the server, e.g. vpn.ss-its.de:51820.",
        lAllowedIps = "Allowed IPs", dAllowedIps = "Which traffic goes into the tunnel. 0.0.0.0/0 = all.",
        lKeepalive = "Keepalive", dKeepalive = "Keeps the link alive (seconds), e.g. 25.",
        appsSection = "Apps (split tunnel)",
        appsInfo = "Choose which apps use the tunnel.",
        appModeAll = "All apps", appModeInclude = "Only these", appModeExclude = "All except these",
        chooseApps = "Choose apps", appsSelected = "selected", searchApps = "Search",
        biometricTitle = "Protect with fingerprint",
        biometricSub = "Secure app start with fingerprint/device lock.",
        autoBootTitle = "Connect after reboot",
        autoBootSub = "Connect automatically when the phone restarts.",
        watchdogInfo = "The watchdog checks every 60 s and additionally every 15 min whether the server IP " +
            "changed, and reconnects automatically.",
        languageTitle = "Language",
        tConfigTooBig = "Config too large", tInvalidConfig = "Invalid config – please check.",
        tFileTooBig = "File too large", tFileError = "Could not read file.",
        tAdded = "Tunnel added", tSaved = "Saved", tDeleted = "Deleted",
    )
}
